platform :ios, '10.0'

require_relative '../node_modules/react-native-unimodules/cocoapods'

target 'spotifyalarm' do
  # Pods for spotifyalarm
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNEventEmitter', :path => '../node_modules/react-native-events'
  pod 'RNSpotify', :path => '../node_modules/rn-spotify-sdk'
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  use_unimodules!

  target 'spotifyalarmTests' do
    inherit! :search_paths
  end
end